@startuml
class Usuario {
  -nome: String
  -id: int
  -senha: String
  +realizarLogin()
}

class Secretaria extends Usuario {
  +gerarCurriculo()
  +manterInformacoesDisciplina(Disciplina)
  +manterInformacoesProfessor(Professor)
  +manterInformacoesAluno(Aluno)
}

class Aluno extends Usuario {
  -matricula: Matricula
  -curso: String
  +matricularDisciplina(Disciplina)
  +cancelarMatricula(Disciplina)
}

class Professor extends Usuario {
  +verificarAlunos(Disciplina)
}

class Disciplina {
  -nome: String
  -codigo: String
  -creditos: int
  -cargaHoraria: int
  -professor: Professor
  +cancelarMatricula(Aluno)
  +verificarMatriculas(): int
  +encerrarDisciplina()
}

class DisciplinasOfertadas {
  -disciplina: Disciplina
  -prazo: Date
  +matricularAluno(Aluno)
}

class Matricula {
  -data: Date
  -status: String
  -tipo: String
  -disciplinas: List<DisciplinaOfertada>
  +notificarCobranca()
  +encerrarMatricula()
}

Secretaria o--> Disciplina : "manter informações" <<Aggregation>>

Professor -- Disciplina : "verificar alunos" <<Association>>

DisciplinasOfertadas *-- Matricula : "gerenciar matriculas" <<Composition>>

DisciplinasOfertadas  -- Disciplina : "Ofertadas" <<Association>>

Matricula -- Aluno : "associar aluno" <<Association>>
@enduml
