@startuml
actor "Secretaria" as Secretaria
actor "Aluno" as Aluno
actor "Professor" as Professor
actor "Relogio" as Relogio

usecase "Gerar Currículo para Semestre" as GerarCurriculo
usecase "Manter Informações sobre Disciplinas" as ManterInformacoesDisciplinas
usecase "Manter Informações sobre Professores" as ManterInformacoesProfessor
usecase "Manter Informações sobre Alunos" as ManterInformacoesAluno
usecase "Efetuar Matrícula" as EfetuarMatricula
usecase "Cancelar Matrícula" as CancelarMatricula
usecase "Verificar Matrículas de Disciplinas" as VerificarMatriculas
usecase "Encerrar Matrícula por Disciplina" as EncerrarMatricula
usecase "Encerrar Disciplina" as EncerrarDisciplina
usecase "Notificar Cobrança" as NotificarCobranca
usecase "Realizar login" as RealizarLogin

usecase "Realizar Matricula Obrigatoria" as MatriculaObrigatoria
usecase "Realizar Matricula Optativa" as MatriculaOptativa

usecase "Verificar alunos matriculados" as VerificarAlunos

Secretaria -up-> GerarCurriculo
Secretaria -left-> ManterInformacoesProfessor
Secretaria -down-> ManterInformacoesDisciplinas
Secretaria -up->  ManterInformacoesAluno

Relogio -down-> VerificarMatriculas

Aluno -up-> EfetuarMatricula
Aluno -down- CancelarMatricula

Professor -down-> RealizarLogin
Professor -up-> VerificarAlunos

Secretaria -> RealizarLogin
Aluno -left-> RealizarLogin

(EfetuarMatricula) .-left-> (MatriculaObrigatoria) : include
(EfetuarMatricula) .-up-> (MatriculaOptativa) : extends

EfetuarMatricula .-right-> EncerrarMatricula : extends
EfetuarMatricula .-right-> NotificarCobranca : include

VerificarMatriculas -> EncerrarDisciplina : "Menos de 3 Alunos Inscritos"
@enduml